@startuml
interface com.Wallet.FilterStrategy.TransactionFilterStrategy {
~ List<Transaction> filter(List<Transaction>)
}

interface com.Wallet.service.UserService {
~ User registerUser(String)
}

class com.Wallet.service.impl.WalletServiceInternalImpl {
- WalletData walletData
+ Wallet createWallet(String)
+ Wallet getWalletByUserId(String)
}


class com.Wallet.model.User {
~ String userId
~ String name
}

class com.Wallet.model.Transaction {
~ String transactionId
~ String payer
~ String payee
~ double amount
~ TransactionType transactionType
~ Timestamp timestamp
~ PaymentMode paymentMode
+ TransactionType getTransactionType()
+ Timestamp getTimestamp()
+ String getPayee()
+ String getPayer()
+ double getAmount()
}


class com.Wallet.FilterStrategy.TransactionFilterStrategyImpl.TransactionTypeFilterStrategy {
~ TransactionType transactionType
+ List<Transaction> filter(List<Transaction>)
}


class com.Wallet.Main {
+ {static} void main(String[])
}

interface com.Wallet.service.WalletServiceClient {
~ Wallet createWallet(String)
~ Double fetchBalance(String)
~ Wallet getWalletByUserId(String)
}

interface com.Wallet.SortStrategy.TransactionSortStrategy {
~ void sort(List<Transaction>,Ordering)
}

class com.Wallet.model.Wallet {
~ String walletId
~ Double balance
+ Double getBalance()
+ void setBalance(Double)
}


class com.Wallet.SortStrategy.TransactionSortStrategyImpl.AmountSortStrategy {
+ void sort(List<Transaction>,Ordering)
}

class com.Wallet.service.impl.UserServiceImpl {
- UserData userData
- WalletServiceInternal walletService
+ User registerUser(String)
}


enum com.Wallet.enums.PaymentMode {
+  DEBIT_CARD
+  CREDIT_CARD
+  UPI
+  CASH_BACK
}

enum com.Wallet.enums.TransactionType {
+  CREDIT
+  DEBIT
+  TOP_UP
}

interface com.Wallet.service.PaymentService {
~ Transaction payment(String,String,Double,PaymentMode)
~ Transaction topUpWallet(String,Double,PaymentMode)
~ List<Transaction> getTransaction(String,TransactionSortStrategy,Ordering,List<TransactionFilterStrategy>)
}

class com.Wallet.exceptions.NoUserFound {
}
class com.Wallet.service.impl.PaymentServiceImpl {
- WalletServiceInternal walletService
- PaymentData paymentData
+ Transaction payment(String,String,Double,PaymentMode)
- void appendTransactionToUser(String,Transaction)
+ Transaction topUpWallet(String,Double,PaymentMode)
+ List<Transaction> getTransaction(String,TransactionSortStrategy,Ordering,List<TransactionFilterStrategy>)
}


class com.Wallet.exceptions.UserAlreadyExist {
}
class com.Wallet.datastore.UserData {
~ Map<String,User> userIdToUser
+ User getUserById(String)
+ Map<String,User> getUserIdToUser()
}


class com.Wallet.FilterStrategy.TransactionFilterStrategyImpl.UserFilterStrategy {
~ String userId
+ List<Transaction> filter(List<Transaction>)
- boolean userfilterUtil(Transaction)
}


class com.Wallet.SortStrategy.TransactionSortStrategyImpl.TimeSortStrategy {
+ void sort(List<Transaction>,Ordering)
}

enum com.Wallet.enums.Ordering {
+  ASC
+  DESC
}

class com.Wallet.datastore.WalletData {
~ Map<String,Wallet> walletIdToWallet
~ Map<String,String> userIdToWalletId
+ Wallet getWalletByUserId(String)
+ Map<String,Wallet> getWalletIdToWallet()
+ Map<String,String> getUserIdToWalletId()
}


interface com.Wallet.service.WalletServiceInternal {
~ Wallet createWallet(String)
~ Wallet getWalletByUserId(String)
}

class com.Wallet.exceptions.NoWalletFoundException {
}
class com.Wallet.service.impl.WalletServiceClientImpl {
- WalletData walletData
+ Wallet createWallet(String)
+ Double fetchBalance(String)
+ Wallet getWalletByUserId(String)
}


class com.Wallet.datastore.PaymentData {
~ Map<String,List<Transaction>> userIdToTransactionList
+ Map<String,List<Transaction>> getUserIdToTransactionList()
}




com.Wallet.service.WalletServiceInternal <|.. com.Wallet.service.impl.WalletServiceInternalImpl
com.Wallet.FilterStrategy.TransactionFilterStrategy <|.. com.Wallet.FilterStrategy.TransactionFilterStrategyImpl.TransactionTypeFilterStrategy
com.Wallet.SortStrategy.TransactionSortStrategy <|.. com.Wallet.SortStrategy.TransactionSortStrategyImpl.AmountSortStrategy
com.Wallet.service.UserService <|.. com.Wallet.service.impl.UserServiceImpl
com.Wallet.exceptions.RuntimeException <|-- com.Wallet.exceptions.NoUserFound
com.Wallet.service.PaymentService <|.. com.Wallet.service.impl.PaymentServiceImpl
com.Wallet.exceptions.RuntimeException <|-- com.Wallet.exceptions.UserAlreadyExist
com.Wallet.FilterStrategy.TransactionFilterStrategy <|.. com.Wallet.FilterStrategy.TransactionFilterStrategyImpl.UserFilterStrategy
com.Wallet.SortStrategy.TransactionSortStrategy <|.. com.Wallet.SortStrategy.TransactionSortStrategyImpl.TimeSortStrategy
com.Wallet.exceptions.RuntimeException <|-- com.Wallet.exceptions.NoWalletFoundException
com.Wallet.service.WalletServiceClient <|.. com.Wallet.service.impl.WalletServiceClientImpl
@enduml