package com.JourneyFramework.enums;

public enum ErrorCode {
    JOURNEY_NOT_FOUND,
    JOURNEY_ALREADY_EXISTS,
    INVALID_STATE_TRANSITION,
    JOURNEY_NOT_ACTIVE,
    USER_ALREADY_ONBOARDED,
    USER_NOT_ONBOARDED,
    INVALID_JOURNEY,
    JOURNEY_EXPIRED;
}
